#include "define.hpp"
#include "tf_utils.hpp"
#include "PuyoGame.hpp"
#include "mcts.hpp"
#include <iostream>
#include <stdio.h>
#include <random>
#include <tensorflow/c/c_api.h>
#include <algorithm>
#include <numeric>