
# ゲーム定義
GAMEMAP_HEIGHT = 13
GAMEMAP_WIDTH = 6
GAMEMAP_SHAPE = (GAMEMAP_HEIGHT, GAMEMAP_WIDTH)
ACTION_KIND = 2*3+(GAMEMAP_WIDTH-2)*4
PUYOS_SHAPE = (2, 2)
PUYO_COLOR = 4
EVALUATE_DEPTH = 10
MAX_STEP = 40
PV_EVALUATE_COUNT = 100
TRY_COUNT = 5
TSUMO_SIZE = 15

# for construction of network
FIELD_CHANNELS = PUYO_COLOR+1
PUYO_CHANNELS = PUYO_COLOR * 4
TURN_CHANNELS = 6
CHANNEL_SIZE = FIELD_CHANNELS + PUYO_CHANNELS
DN_FILTERS = 128
DN_RESIDUAL_NUM = 7
DN_INPUT_SHAPE = (GAMEMAP_HEIGHT, GAMEMAP_WIDTH, CHANNEL_SIZE)
DN_OUTPUT_SIZE = ACTION_KIND

# for training network
RN_EPOCHS = 50
BATCH_SIZE = 128
HEIGHT, WIDTH, CHANNEL = DN_INPUT_SHAPE

# path
RESOURCE_PATH = 'C:/Users/rokahikou/Ohsuga_lab/AlphaPuyo/resources'
DATA_PATH = 'C:/Users/rokahikou/Ohsuga_lab/AlphaPuyo/data'
LOG_PATH = 'C:/Users/rokahikou/Ohsuga_lab/AlphaPuyo/log_eval'
