
# ゲーム定義
GAMEMAP_HEIGHT = 13
GAMEMAP_WIDTH = 6
GAMEMAP_SHAPE = (GAMEMAP_HEIGHT, GAMEMAP_WIDTH)
ACTION_KIND = 22
PUYOS_SHAPE = (2, 2)
PUYO_COLOR = 4
MAX_STEP = 50

# for MCTS
EVALUATE_DEPTH = 5
TSUMO_SIZE = 7
TRY_COUNT = 10
PV_EVALUATE_COUNT = 100
C_PUCT = 5.0

# for construction of network
FIELD_CHANNELS = 5
PUYO_CHANNELS = 16
TURN_CHANNELS = 6
CHANNEL_SIZE = FIELD_CHANNELS + PUYO_CHANNELS
DN_FILTERS = 128
DN_RESIDUAL_NUM = 5
DN_INPUT_SHAPE = (GAMEMAP_HEIGHT, GAMEMAP_WIDTH, CHANNEL_SIZE)
DN_OUTPUT_SIZE = ACTION_KIND

# for training network
RN_EPOCHS = 20
BATCH_SIZE = 128
HEIGHT, WIDTH, CHANNEL = DN_INPUT_SHAPE

THREAD_NUMS = 8

# for selfplay
SP_GAME_COUNT = 150
SP_TEMPERATURE = 1.0

# for evaluate network
EN_GAME_COUNT = 40
EN_TEMPERATURE = 1.0

# path
RESOURCE_PATH = 'C:/Users/rokahikou/Ohsuga_lab/AlphaPuyo/resources'
DATA_PATH = 'C:/Users/rokahikou/Ohsuga_lab/AlphaPuyo/data'
