
# ゲーム定義
GAMEMAP_HEIGHT = 7
GAMEMAP_WIDTH = 4
GAMEMAP_SHAPE = (GAMEMAP_HEIGHT, GAMEMAP_WIDTH)
ACTION_KIND = 2*3+(GAMEMAP_WIDTH-2)*4
PUYOS_SHAPE = (2, 2)
PUYO_COLOR = 3
MAX_STEP = 50

# for construction of network
FIELD_CHANNELS = PUYO_COLOR+1
PUYO_CHANNELS = PUYO_COLOR * 4
TURN_CHANNELS = 6
CHANNEL_SIZE = FIELD_CHANNELS + PUYO_CHANNELS
DN_FILTERS = 128
DN_RESIDUAL_NUM = 6
DN_INPUT_SHAPE = (GAMEMAP_HEIGHT, GAMEMAP_WIDTH, CHANNEL_SIZE)
DN_OUTPUT_SIZE = ACTION_KIND

# for training network
RN_EPOCHS = 30
BATCH_SIZE = 128
HEIGHT, WIDTH, CHANNEL = DN_INPUT_SHAPE

# path
RESOURCE_PATH = 'C:/Users/rokahikou/Ohsuga_lab/AlphaPuyo/resources'
DATA_PATH = 'C:/Users/rokahikou/Ohsuga_lab/AlphaPuyo/data'
